# Use docker compose to launch app locally
version: "3.8"

services:
  app:
    build: .
    container_name: "askpic-container"
    image: "askpic-be"
    ports:
      - "7860:7860"
    volumes:
      - .:/home/user/app
      - /home/user/app/env
      - /home/user/cache
    env_file:
      - .env